version: "3.8"

services:
  db:
    image: postgres:16
    container_name: local_postgres
    environment:
      POSTGRES_USER: prismauser
      POSTGRES_PASSWORD: prismapassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    restart: unless-stopped
